#!/bin/sh /etc/rc.common

USE_PROCD=1
# after network
START=21

ZAPRET_BASE=/opt/zapret
. "$ZAPRET_BASE/init.d/openwrt/functions"

# !!!!! in openwrt firewall rules are configured separately

PIDDIR=/var/run

QNUM=200
NFQWS_USER=daemon
NFQWS="$ZAPRET_BASE/nfq/nfqws"
NFQWS_OPT_BASE="--qnum=$QNUM --user=$NFQWS_USER"

TPWS_USER=daemon
TPPORT=1188
TPWS="$ZAPRET_BASE/tpws/tpws"
HOSTLIST="$ZAPRET_BASE/ipset/zapret-hosts.txt.gz"
[ -f "$HOSTLIST" ] || HOSTLIST="$ZAPRET_BASE/ipset/zapret-hosts-user.txt"
TPWS_OPT_BASE="--user=$TPWS_USER --port=$TPPORT"
TPWS_OPT_BASE4="--bind-addr=127.0.0.1"
TPWS_OPT_BASE6="--bind-addr=::1"
# first wait for lan to ifup, then wait for bind-wait-ip-linklocal seconds for link local address and bind-wait-ip for any ipv6 as the worst case
TPWS_OPT_BASE6_PRE="--bind-linklocal=prefer --bind-wait-ifup=30 --bind-wait-ip=30 --bind-wait-ip-linklocal=3"

run_daemon()
{
	# $1 - daemon string id or number. can use 1,2,3,...
	# $2 - daemon
	# $3 - daemon args
	# use $PIDDIR/$DAEMONBASE$1.pid as pidfile
	local DAEMONBASE=$(basename $2)
	echo "Starting daemon $1: $2 $3"
	procd_open_instance
	procd_set_param command $2 $3
	procd_set_param pidfile $PIDDIR/$DAEMONBASE$1.pid
	procd_close_instance
}

run_tpws()
{
	[ "$DISABLE_IPV4" = "1" ] && [ "$DISABLE_IPV6" = "1" ] && return 0

	local OPT="$TPWS_OPT_BASE"
	local DEVICE

	[ "$DISABLE_IPV4" = "1" ] || OPT="$OPT $TPWS_OPT_BASE4"
	[ "$DISABLE_IPV6" = "1" ] || {
		OPT="$OPT $TPWS_OPT_BASE6"
		network_get_device DEVICE lan
		[ -n "$DEVICE" ] && OPT="$OPT --bind-iface6=$DEVICE $TPWS_OPT_BASE6_PRE"
	}
	run_daemon $1 $TPWS "$OPT $2"

}
stop_tpws()
{
	stop_daemon $1 $TPWS
}


start_service() {
	case "${MODE}" in
		tpws_hostlist|tpws_hostlist_https)
			run_tpws 1 "$TPWS_OPT --hostlist=$HOSTLIST"
			;;
		tpws_ipset|tpws_all|tpws_ipset_https|tpws_all_https)
			run_tpws 1 "$TPWS_OPT"
			;;
		nfqws_ipset_desync|nfqws_all_desync)
			run_daemon 1 $NFQWS "$NFQWS_OPT_BASE $NFQWS_OPT_DESYNC"
			;;
		nfqws_hostlist_desync)
			run_daemon 1 $NFQWS "$NFQWS_OPT_BASE $NFQWS_OPT_DESYNC --hostlist=$HOSTLIST"
			;;
		custom)
	    		existf zapret_custom_daemons && zapret_custom_daemons $1
			;;
	esac
}
